# SPDX-FileCopyrightText: Copyright (c) 2018-2026 Zerocracy
# SPDX-License-Identifier: MIT

[default.extend-words]
# Example keygap value in keygap.md
vOt = "vOt"
Ot = "Ot"
# Part of wallet ID in keygap.md code block
dbe = "dbe"
